name: dusty_flutter
description: "Funny Game: Dusty Island."
version: 0.0.1+12
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: "3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
  flame_tiled: ^1.18.3
  flame_splash_screen: ^0.2.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  flame_noise: ^0.3.0
  collection: ^1.18.0
  flame_audio: ^2.10.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  flame_svg: ^1.10.1
  provider: ^6.1.2
  flame_tiled_utils: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints:
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/loading/
    - assets/tiles/
    - assets/sounds/
    - .env
    - .debug.env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: 04B_30
      fonts:
        - asset: fonts/04B_30__.ttf
    - family: pixelated
      fonts:
        - asset: fonts/pixelated.ttf
    - family: VT323
      fonts:
        - asset: fonts/VT323-Regular.ttf
    - family: "ONEMobilePOP"
      fonts:
        - asset: fonts/ONEMobilePOP.otf
    # - family: "Press Start 2P"
    #   fonts:
    #     - asset: fonts/PressStart2P-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
